<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="Django default" uuid="a329af12-ca6c-4cf1-a35e-5e8b7c1f4c4f">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/cesGroundStation/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:C:\Users\charl\pyworkspace\CES-Ground-Station\db.sqlite3</jdbc-url>
    </data-source>
    <data-source source="LOCAL" name="Django default2" uuid="b70d82f9-0601-4d92-aaeb-462a5e4bf344">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/cesGroundStation/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:C:\Users\charl\pyworkspace\CES-Ground-Station\db.sqlite3</jdbc-url>
    </data-source>
    <data-source source="LOCAL" name="Django default3" uuid="0cfd141b-a261-436b-8406-1769ce0ff18b">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/cesGroundStation/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:C:\Users\charl\pyworkspace\CES-Ground-Station\db.sqlite3</jdbc-url>
    </data-source>
  </component>
</project>